config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :show, :new, :create]

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:show, :index]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product_model.rb
class ProductModel < ApplicationRecord
  belongs_to :supplier
  validates :name, :weight, :width, :height, :depth, :sku, presence: true
  validates :sku, uniqueness: true
  validates :sku, length: { is: 20 }
  validates :weight, :width, :height, :depth, comparison: { greater_than_or_equal_to: 0 }
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :product_model
  validates :brand_name, :corporate_name, :email, :cnpj, presence: true
  validates :cnpj, uniqueness: true
  validates :cnpj, length: { is: 14 }
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
  validates :name, :code, :city, :description, :address, :CEP, :area, presence: true
  validates :code, length: { is: 3 }
  validates :code, uniqueness: true
  validates :CEP, format: { with: /\A\d{5}-\d{3}\z/ }
end

app/controllers/api/v1/warehouses_controller.rb
class Api::V1::WarehousesController < ActionController::API
  def show
    begin
      warehouse = Warehouse.find(params[:id])
      render status: 200, json: warehouse.as_json(except: [:created_at, :updated_at])
    rescue
      render status: 404
    end
  end

  def index
    warehouses = Warehouse.all
    render status: 200, json: warehouses
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @warehouses = Warehouse.all
  end
end

app/controllers/product_models_controller.rb
class ProductModelsController < ApplicationController
  def index
    @product_models = ProductModel.all
  end

  def show
    @product_model = ProductModel.find(params[:id])
  end

  def new
    @product_model = ProductModel.new
    @suppliers = Supplier.all
  end

  def create
    product_model_params = params.require(:product_model).permit(:name, :height, :width,
                                                                 :depth, :weight, :sku,
                                                                 :supplier_id)
    @product_model = ProductModel.new(product_model_params)
    if @product_model.save           
      redirect_to @product_model, notice: 'Modelo de produto cadastrado com sucesso.'
    else
      @suppliers = Supplier.all
      flash.now[:notice] = 'Não foi possível cadastrar o modelo do produto.'
      render 'new'
    end

  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :load_supplier, only: [:show, :edit, :update]

  def index
    @suppliers = Supplier.all
  end

  def show; end

  def new
    @supplier = Supplier.new
  end

  def create
    @supplier = Supplier.new(supplier_params)
    if @supplier.save
      flash[:notice] = "Fornecedor cadastrado com sucesso."
      return redirect_to supplies_path
    else
      flash.now[:notice] = "Não foi possível cadastrar o Fornecedor."
      render 'new'
    end
  end

  def edit; end

  def update
    if @supplier.update(supplier_params)
      flash[:notice] = "Fornecedor atualizado com sucesso."
      redirect_to supplier_path(@supplier.id)
    else
      flash.now[:notice] = "Não foi possível atualizar o Fornecedor."
      render 'edit'
    end
  end

  private 

  def load_supplier
    @supplier = Supplier.find(params[:id])
  end

  def supplier_params
    params.require(:supplier).permit(:corporate_name, :brand_name, :registration_number,
                                     :full_address, :city, :state, :email, :cnpj)
  end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  before_action :load_warehouse, only: [:show, :edit, :update, :destroy]

  def show; end

  def new
    @warehouse = Warehouse.new
  end

  def create
    @warehouse = Warehouse.new(warehouse_params)
    if @warehouse.save
      flash[:notice] = "Galpão cadastrado com sucesso."
      return redirect_to root_path
    else
      flash.now[:notice] = "Não foi possível cadastrar o Galpão."
      render 'new'
    end
  end

  def edit; end

  def update
    if @warehouse.update(warehouse_params)
      flash[:notice] = "Galpão atualizado com sucesso."
      redirect_to warehouse_path(@warehouse.id)
    else
      flash.now[:notice] = "Não foi possível atualizar o Galpão."
      render 'edit'
    end
  end

  def destroy
    @warehouse.delete
    flash[:notice] = "Galpão removido com sucesso."
    redirect_to root_path
  end

  private 

  def load_warehouse
    @warehouse = Warehouse.find(params[:id])
  end

  def warehouse_params
    params.require(:warehouse).permit(:name, :code, :city, :description,
                                      :address, :CEP, :area)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h2>Galpões</h2>

<div>
  <%= link_to 'Cadastrar Galpão', new_warehouse_path %>
</div>

<% if @warehouses.empty? %>
  <p>Não existem galpões cadastrados</p>
<% end %>

<% @warehouses.each do |w| %>
  <%= link_to w.name, warehouse_path(w.id) %>
  <dl>
    <dt>Código: </dt>
    <dd><%= w.code %></dd>
    <dt>Cidade: </dt>
    <dd><%= w.city %></dd>
    <dt>Área: </dt>
    <dd><%= w.area %> m2</dd>
  </dl>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WarehouseApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <header>
      <nav>
        <h1>Galpões & Estoque</h1>
        <%= link_to 'Fornecedores', suppliers_path %> |
        <%= link_to 'Modelos de Produtos', product_models_path %>
      </nav>
    </header>
    <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>

app/views/product_models/index.html.erb
<h1>Modelos de Produtos</h1>

<%= link_to 'Cadastrar Novo', new_product_model_path %>
<% if @product_models.any? %>

  <% @product_models.each do |pm| %>
    <h2><%= pm.name%></h2>
    <dl>
      <dt>SKU</dt>
      <dd><%= pm.sku %></dd>
      <dt>Fornecedor</dt>
      <dd><%= pm.supplier.brand_name %></dd>
    </dl>
  <% end %>

<% else %>
  <p>Nenhum modelo de produto cadastrado.</p>
<% end %>

app/views/product_models/new.html.erb
<h1>Cadastrar Novo Modelo de Produto</h1>

<%= form_with model: @product_model do |form| %>
  <div>
    <div>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    <% @product_model.errors.messages[:name].each do |name_error| %>
      <div class="input-errors">
        <%= name_error %>
      </div>
    <% end %>
  </div>
  <div>
    <div>
      <%= form.label :weight %>
      <%= form.number_field :weight %>
    </div>
    <% @product_model.errors.messages[:weight].each do |weight_error| %>
      <div class="input-errors">
        <%= weight_error %>
      </div>
    <% end %>
  </div>
  <div>
    <div>
      <%= form.label :height %>
      <%= form.number_field :height %>
    </div>
    <% @product_model.errors.messages[:height].each do |height_error| %>
      <div class="input-errors">
        <%= height_error %>
      </div>
    <% end %>
  </div>
  <div>
    <div>
      <%= form.label :width %>
      <%= form.number_field :width %>
    </div>
    <% @product_model.errors.messages[:width].each do |width_error| %>
      <div class="input-errors">
        <%= width_error %>
      </div>
    <% end %>
  </div>
  <div>
    <div>
      <%= form.label :depth %>
      <%= form.number_field :depth %>
    </div>
    <% @product_model.errors.messages[:depth].each do |depth_error| %>
      <div class="input-errors">
        <%= depth_error %>
      </div>
    <% end %>
  </div>
  <div>
    <div>
      <%= form.label :sku %>
      <%= form.text_field :sku %>
    </div>
    <% @product_model.errors.messages[:sku].each do |sku_error| %>
      <div class="input-errors">
        <%= sku_error %>
      </div>
    <% end %>
  </div>
  <div>
      <%= form.label :supplier_id %>
      <%= form.collection_select :supplier_id, @suppliers, :id, :brand_name %>
  </div>
  <%= form.submit 'Enviar' %>
<% end %>

app/views/product_models/show.html.erb
<h1><%= @product_model.name %></h1>

<dl>
  <dt>Fornecedor:</dt>
  <dd><%= @product_model.supplier.brand_name %></dd>
  <dt>SKU:</dt>
  <dd><%= @product_model.sku %></dd>
  <dt>Dimensão:</dt>
  <dd><%= @product_model.height %>cm x <%= @product_model.width %>cm x <%= @product_model.depth %>cm</dd>
  <dt>Peso:</dt>
  <dd><%= @product_model.weight %>g</dd>
</dl>

app/views/suppliers/_form.html.erb
<%= form_with model: @supplier do |form| %>
  <div>
    <div>
      <%= form.label :corporate_name %>
      <%= form.text_field :corporate_name %>
    </div>
    <% @supplier.errors.messages[:corporate_name].each do |corporate_name_error| %>
      <div class="input-errors">
        <%= corporate_name_error %>
      </div>
    <% end %>
  </div>
  <div>
    <%= form.label :brand_name %>
    <%= form.text_area :brand_name %>
    <% @supplier.errors.messages[:brand_name].each do |brand_name_error| %>
      <div class="input-errors">
        <%= brand_name_error %>
      </div>
    <% end %>
  </div>
  <div>
    <%= form.label :full_address %>
    <%= form.text_field :full_address %>
    <% @supplier.errors.messages[:full_address].each do |full_address_error| %>
      <div class="input-errors">
        <%= full_address_error %>
      </div>
    <% end %>
  </div>
  <div>
    <%= form.label :registration_number %>
    <%= form.text_field :registration_number %>
    <% @supplier.errors.messages[:registration_number].each do |registration_number_error| %>
      <div class="input-errors">
        <%= registration_number_error %>
      </div>
    <% end %>
  </div>
  <div>
    <%= form.label :city %>
    <%= form.text_field :city %>
    <% @supplier.errors.messages[:city].each do |city_error| %>
      <div class="input-errors">
        <%= city_error %>
      </div>
    <% end %>
  </div>
  <div>
    <%= form.label :state %>
    <%= form.text_field :state %>
    <% @supplier.errors.messages[:state].each do |state_error| %>
      <div class="input-errors">
        <%= state_error %>
      </div>
    <% end %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.text_field :email %>
    <% @supplier.errors.messages[:email].each do |email_error| %>
      <div class="input-errors">
        <%= email_error %>
      </div>
    <% end %>
  </div>
  <div>
    <%= form.label :cnpj %>
    <%= form.text_field :cnpj %>
    <% @supplier.errors.messages[:cnpj].each do |cnpj_error| %>
      <div class="input-errors">
        <%= cnpj_error %>
      </div>
    <% end %>
  </div>
  <%= form.submit %>
<% end %>

app/views/suppliers/edit.html.erb
<h1>Editar Fornecedor</h1>

<%= render 'form' %>

app/views/suppliers/index.html.erb
<h1>Fornecedores</h1>

<%= link_to 'Cadastrar Novo', new_supplier_path %>
<% if @suppliers.any? %>
  <table>
    <thead>
      <tr>
        <th>Nome</th>
        <th>Localização</th>
      </tr>
    </thead>
    <tbody>
      <% @suppliers.each do |supplier| %>
        <tr>
          <td><%= link_to supplier.brand_name, supplier %></td>
          <td><%= supplier.city %> - <%= supplier.state %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>Não existem fornecedores cadastrados.</p>
<% end %>

<% link_to 'Cadastrar novo fornecedor', new_supplier_path %>

app/views/suppliers/new.html.erb
<h1>Novo Fornecedor</h1>

<%= render 'form' %>

app/views/suppliers/show.html.erb
<h1>Fornecedor <%= @supplier.brand_name %></h1>
<h2><%= @supplier.corporate_name %></h2>

<dl>
  <dt>Documento:</dt>
  <dd><%= @supplier.registration_number %></dd>
  <dt>Endereço:</dt>
  <dd><%= @supplier.full_address %> - <%= @supplier.city %> - <%= @supplier.state %></dd>
  <dt>E-mail:</dt>
  <dd><%= @supplier.email %></dd>
</dl>

<%= link_to 'Editar', edit_supplier_path(@supplier) %>

<div>
  <%= link_to 'Voltar', suppliers_path %>
</div>

app/views/warehouses/_form.html.erb
<%= form_with model: @warehouse do |form| %>
  <div>
    <div>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    <% @warehouse.errors.messages[:name].each do |name_error| %>
      <div class="input-errors">
        <%= name_error %>
      </div>
    <% end %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
    <% @warehouse.errors.messages[:description].each do |description_error| %>
      <div class="input-errors">
        <%= description_error %>
      </div>
    <% end %>
  </div>
  <div>
    <%= form.label :code %>
    <%= form.text_field :code %>
    <% @warehouse.errors.messages[:code].each do |code_error| %>
      <div class="input-errors">
        <%= code_error %>
      </div>
    <% end %>
  </div>
  <div>
    <%= form.label :city %>
    <%= form.text_field :city %>
    <% @warehouse.errors.messages[:city].each do |city_error| %>
      <div class="input-errors">
        <%= city_error %>
      </div>
    <% end %>
  </div>
  <div>
    <%= form.label :address %>
    <%= form.text_field :address %>
    <% @warehouse.errors.messages[:address].each do |address_error| %>
      <div class="input-errors">
        <%= address_error %>
      </div>
    <% end %>
  </div>
  <div>
    <%= form.label :CEP %>
    <%= form.text_field :CEP %>
    <% @warehouse.errors.messages[:CEP].each do |cep_error| %>
      <div class="input-errors">
        <%= cep_error %>
      </div>
    <% end %>
  </div>
  <div>
    <%= form.label :area %>
    <%= form.number_field :area %>
    <% @warehouse.errors.messages[:area].each do |area_error| %>
      <div class="input-errors">
        <%= area_error %>
      </div>
    <% end %>
  </div>
  <%= form.submit %>
<% end %>

app/views/warehouses/edit.html.erb
<h1>Editar Galpão</h1>

<%= render 'form' %>

app/views/warehouses/new.html.erb
<h1>Criar Galpão</h1>

<%= render 'form' %>

app/views/warehouses/show.html.erb
<h2>Detalhes de Galpão</h2>

<div>
  <div>
    Galpão <%= @warehouse.code %>
  </div>
  <div>
    Nome: <%= @warehouse.name %>
  </div>
  <div>
    Cidade: <%= @warehouse.city %>
  </div>
  <div>
    Área: <%= @warehouse.area %> m2
  </div>
  <div>
    Endereço: <%= @warehouse.address %> CEP: <%= @warehouse.CEP %>
  </div>
  <div>
    <%= @warehouse.description %>
  </div>
</div>
<div>
  <%= link_to 'Editar', edit_warehouse_path %>
  <%= button_to 'Remover', @warehouse, :method => :delete %>
</div>
<%= link_to 'Voltar', root_path %>